// Auto-generated by bevel types sync

export type postInput = {
  title: string
}

export type postOutput = {
  id: string
  title: string
}

export const api = {
  post: {
    create: {
      method: 'GET',
      path: '/post',
      input: 'z',
      output: 'postSchema'
    }
  }
}
